### ISSUE TITLE
Preview link does not have https or http protocol

### ISSUE THREAD

**Issue by Mikescops** [nestordedios/bolt-extension-previewlink#5]
Widget view : https://puu.sh/yQazz/18d79bebed.png

Link generated : `://gmex.net/previewlink/posts/16390?key=%242y%2410%24HUGL3MX.wdEK%2Fh%2FIzvGueuF3T6yOksWZX4dJWe.C4mMP5ghilaACy`

Snippet responsible of the protocol in the code `{{ app.request.server.get('HTTP_X_FORWARDED_PROTO') }}`

Additional infos : 
Bolt version: 3.4.5
Extension version: 1.3

**Comment by nestordedios** [comment]
Thanks @Mikescops !! 

It has been fixed and a new release is tagged 👍
